- build.gradle
- winwin-be-api/src/main/java/com/dpm/winwin/api/WinwinApiApplication.java
- winwin-be-api/src/main/resources/application-local.yml
- winwin-be-api/src/main/resources/application.yml
- winwin-be-domain/build.gradle
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/configuration/JpaAuditingConfiguration.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/configuration/QuerydslConfiguration.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/BaseEntity.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/Member.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/category/MainCategory.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/category/MiddleCategory.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/category/SubCategory.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/history/History.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/indict/Indict.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/Post.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/PostGoal.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/talent/MemberTalent.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/talent/Talent.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/CustomMemberRepository.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/MemberRepository.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/impl/CustomMemberRepositoryImpl.java
- gradle 설정
- querydsl 설정
- component scan 설정
- application.yml 설정
원활한 프로젝트 진행을 위해 우선 기본 보일러 플레이트 구성하였습니다.
> 기본 보일러 플레이트 구성

- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/WinwinChattingApplication.java
- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/configuration/WebSocketConfiguration.java
- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/handler/WebSocketHandler.java
- winwin-be-chatting/src/main/resources/application.yml
- application.yml : api의 yml과 같게 설정
- WebSocketConfiguration : 웹소켓을 활성화하기 위해 구현
- WebSocketHandler : 메시지를 알맞은 채팅방에 보내기 위해 구현
- WebSocketHandler에서 채팅관련 로직이 구현된 후 주석 부분을 채우도록 하겠습니다.
궁금한 점
- WebSocketConfiguration에서  endpoint path를 어떤 것으로 하면 좋을지 의견주시면 감사하겠습니다.
- WebSocketHandler 위치를 어디에 두는 것이 좋은건지 궁금합니다. 지금은 handler에 두었습니다.
> 채팅 config, handler 구현

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/dto/ErrorResponseDto.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/enums/ErrorMessage.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/exception/GlobalExceptionHandler.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/error/exception/custom/BusinessException.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/response/dto/BaseResponseDto.java
- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/common/error/dto/ErrorResponseDto.java
- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/common/error/enums/ErrorMessage.java
- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/common/error/exception/GlobalExceptionHandler.java
- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/common/error/exception/custom/BusinessException.java
- winwin-be-chatting/src/main/java/com/dpm/winwin/chatting/common/response/dto/BaseResponseDto.java
각 모듈에서 사용할 성공/실패 시 반환 객체를 구성하였습니다
1. 프로젝트를 구성하면서 해당 PR 처럼 각각 모듈마다 성공/실패를 구성해두어야 할지 아니면 공통 모듈에 두어야 할지 궁굼합니다.
2. 성공/실패 시 응답해주는 값에 HttpStatus 는 두지 않았는데 보통 어떻게 구성하시는지 궁굼합니다.
> 각 모듈에서 사용할 공통 반환 객체 구성

- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/BaseEntity.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/category/MainCategory.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/category/MidCategory.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/category/SubCategory.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/chat/ChatMessage.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/chat/ChatRoom.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/link/Link.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/Post.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/report/Report.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/talent/MemberTalent.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/talent/Talent.java
- 모든 테이블에 생성, 수정 시간 자동화
데이터 추적을 위해 모든 테이블에 추가해주었습니다.
> 생성, 수정 시간 자동화

- winwin-be-api/src/main/resources/application-local.yml
- winwin-be-api/src/main/resources/data.sql
- winwin-be-api/src/test/resources/application.yml
- 카테고리, 멤버 테이블의 더미 데이터 생성
`sql.init.mode` 옵션
- application-local.yml: 테이블을 초기화하여 데이터 생성이 필요할 때만 데이터를 넣어주면 되므로 never 옵션을 주었습니다.
- application.yml: 테스트는 h2 인메모리 DB에서 실행되므로 embedded 옵션을 주어 실행할 때마다 데이터가 생성되도록 해주었습니다.
> feat: 데이터 스크립트 생성

- winwin-be-api/src/main/resources/application-local.yml
- apple 로그인 시 사용되는 redirect url 포트 급하게 수정합니다.
> fix : apple 로그인 시 사용되는 redirect url 수정

- winwin-be-api/src/main/java/com/dpm/winwin/api/category/controller/CategoryController.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/category/service/CategoryService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/category/CustomSubCategoryRepository.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/category/impl/CustomSubCategoryRepositoryImpl.java
> 매칭된 소분류 카테고리 조회 구현

- winwin-be-api/src/main/java/com/dpm/winwin/api/report/controller/ReportController.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/report/dto/request/ReportRequest.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/report/dto/response/ReportResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/report/service/ReportService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/report/Report.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/report/ReportRepository.java
- 게시글에서 사용자를 신고하는 기능을 구현하였습니다.
- 우선적으로 와이어프레임에 존재하는 post에서 사용자를 신고하는 기능을 구현하였습니다.
> 게시글에서 신고 기능 구현

- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/MemberRankReadResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberQueryService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/enums/Ranks.java
- 회원 조회 시 좋아요 1000이 넘었을 때, 1k 1.1k 등으로 나타나게 변경하였습니다.
- 초기 회원 생성 시에 0으로 초기화를 해주었지만, 테스트 시에 회원을 고정했다는 점을 생각하여 null인 경우 0을 넣어주도록 구현이 되어있습니다.
> 좋아요 k 단위 설정

- winwin-be-api/src/main/resources/application-local.yml
> chore : 서버 포트 수정

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
- 로그인 성공 시 멤버Id 담아서 주도록 변경했습니다.
> refactor : 로그인 성공 시 member Id 담아서 보내도록 변경

- winwin-be-api/src/main/resources/application-local.yml
- ssl 설정 제거
- nginx에서 적용 시켜서 제거하였습니다.
> refactor : ssl 설정 제거 (#72)

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/SecurityUtil.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/jwt/TokenProvider.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/report/controller/ReportController.java
- winwin-be-api/src/test/java/com/dpm/winwin/api/member/controller/MemberControllerTest.java
- winwin-be-api/src/test/java/com/dpm/winwin/api/report/controller/ReportControllerTest.java
- 임시로 고정했던 id를 로그인한 회원의 id로 변경하였습니다.
- 이렇게 구현하는 것이 맞는지, 보통 어떻게 가져오는지 궁금합니다.
> 고정된 회원 id -> 현재 로그인한 회원 id 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/response/dto/GlobalPageResponseDto.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/post/dto/response/PostReadResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/post/service/PostService.java
- winwin-be-api/src/test/java/com/dpm/winwin/api/post/controller/PostControllerTest.java
페이징 공통 Response에 두 가지 필드를 추가해주었습니다.
- 현재 페이지 번호
- 현재 페이지의 데이터 수
리뷰 허용 시간 단 10분.
10분 뒤 인질은 죽는다.
> 페이징 공통 Response 필드 추가

- winwin-be-api/src/main/resources/application-local.yml
- 포트 및 서버 설정 변경하면서 리다이렉트 설정도 조금 수정했습니다.
- #76 
- 현재 8080으로 서버 떠있고, 서버에 80에 요청보내면 8080으로 리다이렉트되도록 되어있어서 수정했습니다.
> refactor : 리다이렉트 url 설정 수정

- .github/CODEOWNERS
- winwin-be-api/src/main/resources/application-local.yml
- 애플 리다이렉트 변경으로 배포 합니다. ([링크](https://github.com/depromeet/pingpong-be/pull/78))
> 애플 리다이렉트 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
현재 로그인한 사용자 정보를 반환해주는 API 추가 하였습니다
> 현재 로그인한 사용자 정보를 반환해주는 API 추가

- winwin-be-api/src/main/resources/application-local.yml
- 루트 path로 요청 시 스웨거 보이는거 변경했습니다.
- 루트 입력하면 스웨거 보이는 거 변경했는데, 현재는 루트요청 시 아무 조치 안해서 화이트 라벨 에러 페이지(404) 보여집니다.
> fix : 루트 path(/) 요청 시 swagger-ui 보이는 거 변경

- .github/CODEOWNERS
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
- #83 
- 쿠키 옵션을 주었습니다.
- 도메인
- httpOnly
- samesite
- secure
- 멤버 아이디를 임시로 쿠키에 담아주던 것을 api를 통해 로그인 한 사용자 정보 받아오는것으로 결정하여 제거하였습니다.
- 해성님 코드오너 추가~
close #83
> chore : 쿠키 옵션 설정

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/NicknameGenerator.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/service/AppleLoginService.java
- 임시로 애플에서 받아온 이름을 넣어놨었는데 랜덤 닉네임 추천해주는곳에서 받아서 랜덤으로 닉네임이 들어가도록 변경
- #93 
- 만약에 랜덤 닉네임 추천해주는 서버가 장애가 발생하면 회원가입이 안될거 같은데 이런경우는 보통 어떻게 하나요..?
- 랜덤 닉네임 추천 url : https://nickname.hwanmoo.kr/?format=text&count=1?max_length=30
> feat : 회원가입 시 닉네임 랜덤으로 설정

- .github/workflows/deploy.yml
- winwin-be-api/Dockerfile
- winwin-be-api/Dockerrun.aws.json
- winwin-be-api/src/main/resources/application-prod.yml
> chore: aws beanstalk 설정

- winwin-be-api/src/main/resources/application-prod.yml
- root path에서 swagger로 가는 부분 수정
> root path에서 swagger로 가는 부분 수정

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
- winwin-be-api/src/main/resources/application-dev.yml
- winwin-be-api/src/test/resources/application.yml
- 로그인 성공 시 redirectUri 설정
- 쿠키 도메인 변경
> feat: 로그인 성공 시 redirectUri 설정

- winwin-be-api/src/main/resources/application-dev.yml
- winwin-be-api/src/main/resources/application-local.yml
> chore: ENCRYPT_KEY,pingpong-url 설정

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- responseCookie -> Cookie 객체 변경
> refactor: responseCookie -> Cookie 객체 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
> feat: 쿠키 domain 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/MemberUpdateResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/TalentResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
- winwin-be-api/src/test/java/com/dpm/winwin/api/member/controller/MemberControllerTest.java
> 멤버 프로필 수정 응답 수정

- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/impl/CustomPostRepositoryImpl.java
- 쿼리에서 count랑 fetch join이랑 같이 사용했을때 에러 수정
- 동현님이 작업해야해서 우선 fetch join만 제거해주었습니다.
확인 부탁드립니다.
> fix : 회원별 게시글 조회 쿼리에서 count, fetch 같이 사용해서 나는 에러 해결

- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/MemberRankReadResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/MemberUpdateResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/TalentResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberQueryService.java
- winwin-be-api/src/test/java/com/dpm/winwin/api/member/controller/MemberControllerTest.java
- 회원 프로필 업데이트 응답 복구
- 회원 프로필 조회 응답 변경
소통에 문제가 있었습니다 하하 😯
이전의 변경 사항을 복구하고 요청 받은 API의 응답을 추가하였습니다.
> fix: 회원 프로필 조회 응답 수정

- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/impl/CustomPostRepositoryImpl.java
- 게시글 목록 조회할 때, (main/mid/sub)categoryId 파라미터가 0일 경우 무시하도록 처리해주었습니다.
> feat: 조건 파라미터가 0일 경우 무시하도록 처리

- winwin-be-api/src/main/resources/application-dev.yml
- winwin-be-api/src/main/resources/application-prod.yml
- dev, prod 환경 별로 redis 설정을 해주었습니다.
> chore : 운영 환경별 redis host 설정

- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/enums/Ranks.java
- 랭크 목록 조회 시에 필요한 이미지를 실제 url 값으로 변경해주었습니다.
> feat: rank 이미지 url 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/post/service/PostService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/dto/link/LinkDto.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/link/Link.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/Post.java
- link 없는 경우 예외 처리를 해주었습니다.
- request의 links에서 link 객체로 변환해주는 비즈니스 로직을 엔티티 클래스로 이동해주었습니다.
> fix: link 없는 경우 예외 처리

- .github/workflows/dev-deploy.yml
- .github/workflows/prod-deploy.yml
- winwin-be-api/Dockerfile-dev
- cicd : develop 머지 시 개발서버에 배포되도록 설정
- develop 머지 시 개발서버에 배포되도록 설정하였습니다.
> cicd : develop 머지 시 개발서버에 배포되도록 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
- 로그인 후 기본 리다이렉트 url을 /nickname/ 으로 해달라고 프론트에서 요청해서 변경했습니다.
> fix : 기본 리다이렉트 url 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
> refactor : cors 설정 변경

- winwin-be-api/src/docs/asciidoc/post-api.adoc
- winwin-be-api/src/test/java/com/dpm/winwin/api/post/controller/PostControllerTest.java
> test: 좋아요 API 테스트코드 작성

- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/post/Post.java
- 엔티티 컬럼 사이즈 변경 (varchar 255 -> 500)
- 사용하지 않는 컬럼 제거
db에도 변경분을 반영해주었습니다~
> refactor: 엔티티 컬럼 속성 추가

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
- 전체 다 열어줬던 인증 설정을 /test, /home, /apple/redirect 만 열어주도록 변경했습니다.
- 혹시 더 필요하면 코멘트 부탁드립니다.
> chore : 개발 편의상 시큐리티 설정 열어둔 부분 변경

- winwin-be-api/src/main/resources/application-prod.yml
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- 운영 서버 rds 세팅
- Member 엔티티의 likeCount 필드 속성 추가
- 프로덕션용으로 세팅하였습니다.
- `utf8mb4` 문자 인코딩해주었습니다 (이모지 저장을 위함)
- likeCount DB 설정 변경
> feat: 운영 서버 rds 세팅

- winwin-be-api/src/main/resources/application-dev.yml
- winwin-be-api/src/main/resources/application-local.yml
> chore : 개발용 db 접속정보 업데이트

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
헬스 체크 API 는 스프링 시큐리티 필터 체인을 거치지 않도록 개선하였습니다
> refactor: 헬스 체크 API 인증/인가 제외

- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
- 처음 로그인 한 경우가 아니라면(닉네임이 이미 존재하는 경우) /main으로 리다이렉트 시키도록 하엿습니다.
> chore : 닉네임이 있는경우 /main으로 리다이렉트

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfigDev.java
-  dev 환경인 경우 모두 인증 안해도 되도록 임시 변경
- 프론트에서 작업 할 때 dev환경에 api 요청 보내는거는 로컬에서 보낸다해서 security config profile 둬서 dev의 경우 모두 인증안하도록 변경했습니다.
> chore : dev 환경인 경우 모두 인증 안해도 되도록 변경

- .github/workflows/dev-deploy.yml
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- 자바스크립트로 쿠키 접근하기 위해서 httpOnly 설정 false 로 변경
- 테스트 편의를 위해 GitHub Action dev deploy 시 manual trigger 할 수 있도록 추가
> config: cookie httpOnly false 로 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- 자바스크립트로 쿠키 접근하기 위해서 httpOnly 설정 false 로 변경 (일부 API에서 쿠키 접근을 필요로 하여 재변경하였습니다)
> config: cookie httpOnly false로 변경

- .github/workflows/dev-deploy.yml
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
> config: httpOnly true를 false로 변경하고, cors 문제를 해결

- winwin-be-api/src/main/java/com/dpm/winwin/api/auth/service/AuthService.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/common/utils/CookieUtil.java
- 로그아웃 시 기존 방법에 브라우저의 쿠키가 삭제가 안되어서 로그인 했을때 방법으로 쿠키 값을 없애는 방법으로 변경했습니다
> refactor : 로그아웃 시 쿠키 삭제하는 방법 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/member/controller/MemberController.java
> refactor : 멤버 탈퇴시에도 쿠키 삭제하도록 수정

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/HttpCookieOAuth2AuthorizationRequestRepository.java
- 현재 다른사람들 아이폰에서 제대로 애플 로그인 페이지로 안넘어가서 user-agent 정보 확인하기 위해 로그 추가했습니다.
> chore : 유저 에이전트 정보 로깅

- winwin-be-api/src/main/java/com/dpm/winwin/api/post/controller/PostController.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/post/service/PostService.java
- winwin-be-api/src/test/java/com/dpm/winwin/api/post/controller/PostControllerTest.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/CustomPostRepository.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/impl/CustomPostRepositoryImpl.java
- 게시물 Block 기능 구현
- #153 
재능 게시물 목록 조회 API, 맞춤 재능 게시물 목록 조회 API를 수정하였습니다!
> feat: 게시물 Block 기능 구현

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/HttpCookieOAuth2AuthorizationRequestRepository.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- 회원 탈퇴 시 게시글도 함께 삭제되도록 변경하였습니다.
> refactor : 회원 탈퇴 시 게시글 함께 삭제되도록 변경 (#157)

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/HttpCookieOAuth2AuthorizationRequestRepository.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/post/LikesRepository.java
> refactor : 멤버 삭제 시 좋아요 삭제되도록 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/configuration/SecurityConfig.java
- winwin-be-api/src/main/resources/application-prod.yml
-prod, dev 디비 통합해서 사용하는것으로 하겠습니다.
> chore : 디비 통합

- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/request/MemberUpdateRequest.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- 받고 싶은 재능, 주고 싶은 재능 null 허용으로 변경해주었습니다. (기능 구현이 시급해서 조금 하드하게 올렸습니다)
> refactor: 멤버 수정 API request validation 변경 및 예외 처리

- winwin-be-api/src/main/java/com/dpm/winwin/api/jwt/TokenResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/service/AppleLoginService.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- 앱 심사 내용에 따라 애플에서 제공해주는 유저 이름 사용하도록 수정했습니다.
> refactor : 애플에서 제공해주는 유저 이름 사용하도록 수정

- winwin-be-api/src/main/java/com/dpm/winwin/api/jwt/TokenResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/dto/response/MemberRankReadResponse.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberCommandService.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/member/service/MemberQueryService.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/controller/AppleLoginController.java
- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/service/AppleLoginService.java
- winwin-be-api/src/main/resources/application-dev.yml
- winwin-be-api/src/main/resources/application-local.yml
- winwin-be-api/src/main/resources/application-prod.yml
- winwin-be-api/src/test/java/com/dpm/winwin/api/member/controller/MemberControllerTest.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/entity/member/Member.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/dto/response/MemberReadResponse.java
- winwin-be-domain/src/main/java/com/dpm/winwin/domain/repository/member/impl/CustomMemberRepositoryImpl.java
> refactor :  애플에서 유저 이름 안받도록 변경

- winwin-be-api/src/main/java/com/dpm/winwin/api/oauth/service/AppleLoginService.java
- 회원 데이터 없을경우 404 대신 회원 데이터 추가하도록 변경
> refactor: 로그인 시 소셜 아이디 값 없는 회원인 경우 데이터 저장
